#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config /home/geovane/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
polybar-msg cmd quit &
polybar &
feh --bg-scale ~/Imagens/wallpaper2.jpg &
dunst &
xset b off
xss-lock --transfer-sleep-lock -- i3lock -f -e --nofork &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a steam state=floating
bspc rule -a discord state=floating
bspc rule -a Spotify state=floating
bspc rule -a simple-scan state=floating
bspc rule -a feh state=floating
bspc rule -a gnome-calculator state=floating
